### ISSUE TITLE
"yarn add" error spawn E2BIG

### ISSUE THREAD

**Issue by mpalpha** [nuxt-community/mdx-module#21]
**Describe the bug**
@nuxtjs/mdx does not install via yarn

**To Reproduce**
1. Go to your project in terminal.
2. type 'yarn add --dev @nuxtjs/mdx' and press enter
3. wait.

**Expected behavior**
module to install without error.

**Screenshots**
none.

**Desktop (please complete the following information):**
 - OS: darwin x64
 - Version catalina

**Additional context**
yarn-error.log
Arguments: 
  /Users/*****/.nvm/versions/node/v12.18.4/bin/node /usr/local/Cellar/yarn/1.22.10/libexec/bin/yarn.js --cwd docs

PATH:
...

Yarn version: 
  1.22.10

Node version: 
  12.18.4

Platform: 
  darwin x64

Trace: 
  Error: spawn E2BIG
      at ChildProcess.spawn (internal/child_process.js:407:11)
      at Object.spawn (child_process.js:548:9)
      at /usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:25829:24
      at new Promise (<anonymous>)
      at new F (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:5301:28)
      at /usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:25828:12
      at run (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:43133:7)
      at BlockingQueue.maybePushConcurrencyQueue (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:43148:7)
      at BlockingQueue.shift (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:43143:10)
      at /usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:43087:15

**Comment by mpalpha** [comment]
npm install doesn't work either, as it is stuck in a loop.

```
$ yarn --cwd docs
yarn install v1.22.10
[1/4] 🔍  Resolving packages...
success Already up-to-date.
$ yarn --cwd docs
yarn install v1.22.10
[1/4] 🔍  Resolving packages...
success Already up-to-date.
...
...
...
```

**Comment by nobalmohan** [comment]
I too faced this issue.I manually added ""@nuxtjs/mdx": "0.0.1"," to package.json and did a "npm install". It's working now
